name: Add issues and PRs to the Apollo project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add to Apollo project
    uses: openedx/.github/.github/workflows/add-issue-to-a-project.yml@master
    secrets:
      GITHUB_APP_ID: ${{ vars.APOLLO_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.APOLLO_APP_SECRET }}
    with:
      ORGANIZATION: eduNEXT
      PROJECT_NUMBER: 1
