name: PR-Issue assignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.APOLLO_APP_ID }}
          application_private_key: ${{ secrets.APOLLO_APP_SECRET }}
      - name: Auto-assign PR-Issue
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ steps.get_workflow_token.outputs.token }}
          teams: dedalo
